backend/models/__init__.py
from flask_sqlalchemy import SQLAlchemy
from .db import db
from .user import User

backend/models/db.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

backend/models/user.py
from .db import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    _password = db.Column(db.String(255), nullable=False)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
        self._password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
        }

backend/forms/__init__.py
from .signup import Signup
from .login import Login

backend/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, ValidationError
from ..models import User

def user_exists(form, field):
    name = field.data
    user = User.query.filter(User.name == name).first()
    if not user:
        raise ValidationError("Username provided not found!")

def password_matches(form, field):
    password = field.data
    print("FORM DATA", form.data)
    name = form.data["name"]
    user = User.query.filter(User.name == name).first()
    print("USERNAMNE", name)
    if not user:
        raise ValidationError("No such user exists.")
    if not user.check_password(password):
        raise ValidationError("Password was incorrect.")

class Login(FlaskForm):
    name = StringField("name", validators=[DataRequired(), user_exists])
    password = StringField("password", validators=[DataRequired(),
                                                   password_matches])

backend/forms/signup.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired, ValidationError
from ..models import User

def user_exists(form, field):
    username = field.data
    user = User.query.filter(User.name == username).first()
    if user:
        raise ValidationError("Username already exists!")

class Signup(FlaskForm):
    username = StringField("username", validators=[DataRequired(), user_exists])
    password = StringField("password", validators=[DataRequired()])

backend/__init__.py
from flask import Flask, jsonify
from .config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect, generate_csrf
from .commands import seed_commands, select_commands
from flask_login import LoginManager
from flask_cors import CORS

from .models import db, User
from .routes import auth as auth_blueprint
from .routes import main as main_blueprint

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    Migrate(app, db)

    # CORS policy takes all cross-site origins! See docs for ammendments.
    CORS(app)

    app.register_blueprint(auth_blueprint, url_prefix="/api/auth")
    app.register_blueprint(main_blueprint, url_prefix="/api")

    app.cli.add_command(seed_commands)
    app.cli.add_command(select_commands)

    login_manager = LoginManager(app)
    login_manager.login_view = "auth.unauthorized"

    # Build docs from docstrings in view functions!
    # @app.route("/api/help")
    # def api_help():
    #     route_list = { rule.rule: app.view_functions[rule.endpoint].__doc__
    #                    for rule in app.url_map.iter_rules()
    #                    if rule.endpoint != 'static' }
    #     return route_list

    # FIXMEEEEE: csrf injection is not very safe,
    # we should use stateless mechanism to do this--custom headers?
    @app.after_request
    def inject_csrf_token(response):
        response.set_cookie(
            "csrf_token",
            generate_csrf(),
            secure=False,
            samesite=None,
            httponly=True
        )
        return response

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    
    return app

backend/commands/__init__.py
from ..models import db, User
from flask.cli import AppGroup
from werkzeug.security import generate_password_hash

def seed_users():
    debug = User(name="debug",password="debug")
    db.session.add(debug)
    db.session.commit()

def undo_users():
    db.session.execute("DELETE FROM users")
    db.session.commit()

seed_commands = AppGroup("seed")
@seed_commands.command("all")
def seed():
    seed_users()

@seed_commands.command("undo")
def undo():
    undo_users()

@seed_commands.command("restore")
def restore():
    db.drop_all()
    db.create_all()

select_commands = AppGroup("select")
@select_commands.command("users")
def select_users():
    print("Printing all users...")
    users = db.engine.execute("SELECT * FROM users")
    print(users.fetchall())

backend/routes/__init__.py
from .main import main
from .auth import auth

backend/routes/auth.py
from flask import (Blueprint, render_template,
                   redirect, url_for, flash, request)
from werkzeug.security import (generate_password_hash,
                               check_password_hash)
from ..forms import Signup, Login
from ..models import db, User
from flask_login import (login_user, logout_user,
                         login_required, current_user)

auth = Blueprint("auth", __name__)

# template route
# @auth.route("/login")
# def login():
#     form = Login()
#     return render_template("login.html", form=form)

def gen_err_response(form_errors):
    return [f"{k}: {err}"
            for k,errs in form_errors.items()
            for err in errs]

@auth.route("/")
def authenticate():
    """Authenticates a user"""
    if current_user.is_authenticated:
        return current_user.to_dict()
    return {"errors": ["Unauthorized"]}

@auth.route("/unauthorized")
def unauthorized():
    """Returns unauthorized JSON when flask-login auth fails"""
    return {"errors": ["Unauthorized"]}, 401

@auth.route("/login", methods=["POST"])
def login_post():
    """Logs a user in"""
    form = Login()
    form["csrf_token"].data = request.cookies["csrf_token"]
    if form.validate_on_submit():
        user = User.query.filter(User.name == form.data["name"]).first()
        login_user(user)
        return user.to_dict(), 200
    return {"errors": gen_err_response(form.errors)}, 401

@auth.route("/logout")
def logout():
    """Logs a user out"""
    logout_user()
    return {"message": "User logged out"}

@auth.route("/signup")
def signup():
    form = Signup()
    return render_template("signup.html", form=form)

@auth.route("/signup", methods=["POST"])
def signup_post():
    form = Signup()
    form["csrf_token"].data = request.cookies["csrf_token"]
    if form.validate_on_submit():
        unsafe_user = User()
        form.populate_obj(unsafe_user)
        new_user = User(name=unsafe_user.username,
                        password=generate_password_hash(unsafe_user.password))
        db.session.add(new_user)
        db.session.commit()
        return new_user.to_dict(), 200
    return {"errors": gen_err_response(form.errors)}, 401

backend/routes/main.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render_template("index.html")

@main.route("/profile")
@login_required
def profile():
    return render_template("profile.html", name=current_user.name)

backend/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>
<body>
    <section class="hero is-primary is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>
</html>

backend/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}

backend/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        <form method="POST" action="/api/login">
	  {{form.csrf_token}}
	  <div class="field">
	      <div class="control">
		{{form.name(class_="input is-large", placeholder="Username")}}
	      </div>
	  </div>
	  <div class="field">
	      <div class="control">
		{{form.password(class_="input is-large", placeholder="Password", type="password")}}
	      </div>
	  </div>
	  <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

backend/templates/profile.html
{% extends "base.html" %}
{% block content %}
<h1 class="title">
  Welcome, {{name}}!
</h1>
{% endblock %}

backend/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        <form method="POST" action="/api/signup">
	  {{form.csrf_token}}
            <div class="field">
                <div class="control">
		    {{form.name(class_="input is-large", placeholder="Username")}}
                </div>
            </div>
            <div class="field">
                <div class="control">
		    {{form.password(class_="input is-large", placeholder="Password", type="password")}}
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}